[goConfig]
maxLimit = "800"
timeOut = "3"

[elastisearchDB]
elastisearchServer ="127.0.0.1" # elastic ip
elastisearchPort ="9200" # elastic port
elastisearchUsername = "elastic" # elastic user
elastisearchPassword = "" # elastic password
elastisearchIndex = "" #index elastic

[database]
server = "127.0.0.1" # server IP
port = "5299" # server port
database = "syncDB" # server DB Name
user = "sa" # server USER
password = "" # server credentials

[output]
directory = "./output"
format = "toml"

